### ISSUE TITLE
【羣】不能转换为【群】

### ISSUE THREAD

**Issue by 775405984** [tongwentang/New-Tongwentang-for-Chrome#10]
如题

**Comment by softcup** [comment]
根據「教育部重編國語辭典修訂本」的敘述，「羣」是「群」的異體字，所以「羣」沒必要轉為「群」

參考： http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=W00000103808

**Comment by 775405984** [comment]
原来是台湾的大神，幸会幸会！
不过话说回来，这个「群」字在大陆这边属于官方正体字，而另外一个字（抱歉，手机打不出来），在大陆根本没人知道，更不用说使用了。
所以，我建议，如果繁体转换成简体字，可以多一个选项，去掉不常用的异体字。
如有冒犯，请多多见谅！
