### ISSUE TITLE
Please add keyboard shortcuts

### ISSUE THREAD

**Issue by Filip013** [tongwentang/New-Tongwentang-for-Chrome#12]
Hi, I love your extension and I use with Duolingo and Clozemaster which have dynamic content and the characters change quickly without the page being reloaded. So it would be very useful if you would add support for keyboard shortcuts so that I can avoid having to use the mouse. Thanks in advance!

**Comment by Filip013** [comment]
Hi, I hope I'm not bothering you with this. Is there any hope of keyboard shortcuts being added. I would really like to learn Traditional characters but Duolingo only teaches simplified characters. Keyboard shortcuts would make learning a lot easier.

**Comment by PJCHENder** [comment]
I use Option + Shift + C on my Mac which can invoke the translation. You can try on you Mac.
