### ISSUE TITLE
所有 constructor 會轉換為 function Object() { [native code] }

### ISSUE THREAD

**Issue by doggy8088** [tongwentang/New-Tongwentang-for-Chrome#15]
我發現透過新同文堂翻譯文章的時候 (簡體轉繁體)，所有 `constructor` 都會轉換為 `function Object() { [native code] }`，我想這應該是個 Bug。

**Comment by doggy8088** [comment]
@softcup Will you release new version onto Chrome Web Store recently?

**Comment by softcup** [comment]
你好：

目前外出掃墓中，今天晚上會來更新。

謝謝。

Will 保哥 <notifications@github.com> 於 2018年4月4日 週三 11:40 寫道：
