### ISSUE TITLE
FaceBook第一次加载页面可转换，往下滚动后几屏不能自动转换，能实时转换吗？

### ISSUE THREAD

**Issue by ghost** [tongwentang/New-Tongwentang-for-Chrome#9]
RT，请问有办法吗？FF的梅花繁简转换可以做到，可是没有CR版本，望能改进，感谢！

**Comment by ljxprime** [comment]
把 `tongwen_chrome.js` 里面的转换由一次性的换成定时的就可以了（比如用 `setInterval`）。
https://github.com/softcup/New-Tongwentang-for-Chrome/blob/master/tongwen_chrome.js#L60
https://github.com/softcup/New-Tongwentang-for-Chrome/blob/d8c7975b5b292aef2212cc2c1251fd042ece0c36/tongwen_chrome.js#L62

**Comment by codehz** [comment]
@ljxprime 不需要定时吧，直接监听dom子树修改并做防抖动处理不就好了

**Comment by softcup** [comment]
直接監聽 dom 的異動，若沒處理好會造成效能低落，曾經試過但是那個效果有點慘不忍睹，就先放棄不處理了。

**Comment by doggy8088** [comment]
@softcup 或許可以增加個選項設定，在「自動轉換規則」的地方，讓 User 可以設定是否要定時幾毫秒自動重新執行繁簡轉換。
